CREATE DATABASE promospy_db;

CREATE USER promospy WITH ENCRYPTED PASSWORD 'S2vqPFySp32wFD';

GRANT CONNECT ON DATABASE promospy_db TO promospy;

\c promospy_db

GRANT USAGE ON SCHEMA public TO promospy;
GRANT CREATE ON SCHEMA public TO promospy;
GRANT ALL PRIVILEGES ON ALL TABLES IN SCHEMA public TO promospy;

ALTER DEFAULT PRIVILEGES IN SCHEMA public
GRANT ALL ON TABLES TO promospy;

