server {
    listen 80 default_server;

    location /rabbitmq/ {
        proxy_pass http://nginx_rabbitmq:15672/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }

    location / {
        return 200 "Nginx online\n";
    }
}

