worker_processes auto;

events {
    worker_connections 1024;
}

stream {
    # ===== RabbitMQ =====
    upstream rabbitmq_backend {
        server nginx_rabbitmq:5672;
    }

    server {
        listen 6380;
        proxy_pass rabbitmq_backend;
    }

    # ===== Postgres =====
    upstream postgres_backend {
        server nginx_postgres:5432;
    }

    server {
        listen 5433;  # porta externa
        proxy_pass postgres_backend;
    }
}

